spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hobbyboard
    username: hanchang-yun
    password: hobbyboard
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: K1Kpaq1wmlwrXeWWbFpF
            client-secret: KhuqRqrNCh
            redirect-uri: http://localhost:8080/member/naver/callback
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response


server:
  servlet:
    jsp:
      init-parameters:
        development: true

jwt:
  expiration_time: 86400000
  secret: VqwrasfgtasQWSR124TRAsr1gS51FDrasrqQpsfqwrqwr24


logging:
  level:
    org.slf4j: debug
    org.springframework.security: debug
    HobbyBoard.domain.member: debug
    HobbyBoard.global.config: debug
    org.hibernate.SQL: debug
